language: ruby
before_install:
- gem update --system
- gem --version
deploy:
  provider: heroku
  api_key:
    secure: Slk2oRxRn4B9Dui/Q0I/wAzEmvRi0/gEJI51mmSa09LxvOl5aobyFhKouvz67LKELc0Vk/wADDETiREwUhD723KCzKoDApUt9tQ9e3F2oQrt41OBmGMYmxVqpVFo9wTgpyTn8KGlDup5ntPP6oPZ5jMMObROykGRMzqyop9bhzF+Jys9XFLh3OlH9/2C2cn2O+5Ose/nFL6/kTlkBJ5k8pXMQHFjryYcQ+1R6YpXyKalY+iioKXwb+xW3LRESgscOo3NYDaMbbAQznuuj3PmSEKayCyKpwfcXqGGV+ql4IePClQg/R8CvMX9v5oXwPkDX85nUuDYvtnZk0e8K0UOqGsjhBvZoZpVoJ30h9tIGvSG1bTmaNoPtDphMa7JX83eLMASXsYzTy1Zukfi3DEKhw5yimptzpFGj7mnVpnosJViH+FTVje20EAy/cA8leSVJ1BabSNEIkP0a9tBQfwAKE8ycnH5c4HHkUMvwOG9BOQHgsWQ1u9OtmMn8Odp9GgXrkDhHdWwjZ4DUsuQCqHXSkAMm/fjnqKcJq0CN7P+cL3ra+biHkxZoShDA7SAXbdb79HANEbBh6rDqnBdmWoT7kTIXrh6l42jSN1iEMu+2ku75bccEwKmkBImPcsaia5dmWTVJ0xeKtx29nk42YrviwIfGxLcEJtCu7v8RVE1Deo=
  app: heikkiheibrews-dev
