language: ruby

before_install:
- gem update --system
- gem --version

before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate

deploy:
  provider: heroku
  api_key:
    secure: "TgoMlMaHNIyJCgPyc8Rugo7HNBjN1nKm9ZMg73vLA5xp5+LuAm8uewr2A9FQXpsY2Wu0d9Y9OkSswoLsdOeElITqFzXfbqijGxQHbA7l3R8kLZAuiMUqjDy6iDO/wddaf77wGNfLvZ2FfvT+X0n2uqQvmbWG+8Ppv20Iw15Ay9Sf+q1WcOKzndFmuDjelvX0m8tYuZ4FLttXRRI9vnn+ixFo48COwaNzupnn2iOOKE8jMJG2DEdr6aGtCzLBZl6eiov6y31o5gbm20iK5WNF2OwuhDb+R0tMbGelirEtmk5BV34NKHOOeXvYkEX2yDqrMSX0gfphlIaJv00YPK9PS4ii3Fh4p4PAEc9wfp/h159DBiaQ+AL+V5YFO1gKnIr+pPVo8KUZavFRPnwYSGnfxUnA7B0uk9FcB1JAo+wjW0Ks4/ORpP2xHP5RMaQ9pKoAXbcloRp41EfUrgZAFMsqDHM2pl1B/RiDx8fXr0FROKFy23ekLFRRvr7PWzMnomQ6jFbnekllBvawYr7Bnmf7cdESkech40BClTjhuh9TexE5GKKPGIMpZ7kwYiWng8BS20jyRokHX3ZTVWVug/nlTbi494BCpO775ALQWqdp5IOVp3A6IiC6t9f0OFAztYA2ZYXnCILZ604Tylhh85DNG7taPjmAnzRiHZ2VrGuBMSI="
  app: heikkiheibrews-dev
  on:
    repo: HeikkiHei/ratebeer
    branch: week2