language: ruby
before_install:
- gem update --system
- gem --version
deploy:
  provider: heroku
  api_key:
    secure: c0eyVjMRbIDf8mKzbibtv/tpqwnG1ZVt6KXfqOilK0+0LoFUaUTalVjR97zgr/mLA+9EirhSz+R0fD3mD4NgIpVY1kr2+1YgHYpVRmSy4D61fHwIM1h8WkXLYgXT98CaNm2/QjlBLFcpaTTz24ftY7vA0V65RKhnfeM9XcGpJbh9lBR7a1VlU7Mjf7yfY3UJ2n4A968f3tR1oBx//rwlHmZ75whrIv6tciCuAklWnHlIau1+K8IyFGLkEY0cF+yWOk4rH7YPIoCr8e1aFbQNINKRl0Le5QuP8qnUNKBDnpjZWqIZDaiJCoeg8SZL6LlvDlrd5KxLhSx6L8yhx/gNRaJgThgyb3o1B6xpL4rSpLkUCNd89uixQWA4uqB9YDuvQ0VNn9YqMsXduKouQPh+t5QsTGmlBEjrEaVuwkAI9qsLnePS8ncTeSio0lyp3Sjh5iiBkbbiflIjY+ftsS/V1rG94XCo/GyhFDBzmR/1o7ee2mpR/Eub2dhqPcDhl949F4IXyG46p3p0HL8+kSAq3wnH8ruQ5GqEDBiJIGORv2vIG5i+lWSj7hDiKatFlCSOkkC3eYEuM2hySEWT0YHG664R2Ls5x+O292R6vLmAl2jSQfUqftz8NsccFFDr148mv6tOOk36y5pOay0BuaFUypSH0w3qFJ6KN118lOY7ur8=
  app: heikkiheibrews-dev
  on:
    branch: week2
