language: ruby

before_install:
- gem update --system
- gem --version

before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate

deploy:
  provider: heroku
  api_key:
    secure: fwcfxhzeqdbX0H6eGUxd77F3074Oed1aa4uQATNz2Y/+0R0/eSsOLYOwHePcv42MsQhP+WNxZouA/devN+DCJBIq/BEwx1FPkRIntzQHC5klOzyv1pkWvu7VnXKgy9hmYmn5GEJ34m4/QCym7FUggPm6jGEtoMKw01YFBCkgqvqfrI88uXvlYP+BE5hNoO+qclRK028UaDlM679k/6xEVnUQBDY8doRzdZSFoFkWXM40fKVLnIirn+Dm0MYAqZiuR4dPYWbgitE8U7rNZxBcdKaJtfHNJ7fy6rhgdfu7s7b/gjGAJRq4wYzVXmNzxQ757gdPoaKTyAao7pm6vmrkBNIQhRYGHrWyjN7DGNyS57ffq8GR6SGUUxgNgpdTygIfem+IaDmXbYlZraMN7eq51FH/9xwCh3qk+GRwVCbGnbFAOvoF+HSU+eUICe2oRrGKvLXgvw/52UF+Zqjwz9shMveLuGkndGZKkKa0jkTudKhpbRWx8KquZ4/v+cL2c6mDLmV1AX50CmvuG52/QMTwxgrudr2RVxuxbGEsZxlNW+Jc49nF4Gal0IRT0zMYzgNWCtd+0TX8kvI8wu1XdFPyPrmOEDD9EeUDU70um+v4PWv+oPlNlpzT5nOWsbjzVAOsOZGGGULc25ohAq/kVFYgOMVg90jgrCPPhNpj/372gQA=
  app: heikkiheibrews-dev
  on:
    repo: HeikkiHei/ratebeer
    branch: week2